"""fix_attempts_created_at_default

Revision ID: c77a83b6b43b
Revises: fd431669c7a7
Create Date: 2026-06-19 16:11:06.251909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77a83b6b43b'
down_revision: Union[str, Sequence[str], None] = 'fd431669c7a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'created_at',
        server_default=sa.text('now()'),
        nullable=False
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
